import { Product } from "./types";

import { People } from "./types";
import i1 from '../public/romeena.jpeg'
import i2 from "../public/images.jpeg"
import i3 from "../public/person.jpeg"
import i4 from "../public/person4.jpeg"
import i5 from "../public/i5.jpeg"


export const products: Product[] = [
  {
    id:1,
    title: "Brown Sweater",
    image: ["/picst/aweater.jpeg"],
    slug: "brown-sweater",
    description: "Best women top.Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos voluptatum, accusamus deserunt eius blanditiis recusandae beatae illo ",
    price: 150,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:2,
    title: "Pink Beaded Bracelet",
    image: ["/picsj/beadedpinkbracelet.jpeg"],
    slug: "beadedpinkbracelet",
    description: "Best women accesssories lorem",
    price: 70,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 10,
  },
  {
    id:3,
    title: "brown-pointedtoe-pumps.avif",
    image: ["/picss/brown-pointedtoe-pumps.avif"],
    slug: "brown-pointedtoe-pumps.avif",
    description: "Best women shoes lorem",
    price: 120,
    catogery: "shoes",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 25,
  },
  {
    id:4,
    title: "Black Jacket",
    image: ["/picst/blackjacket.webp", "/picst/blackjacket0.webp"],
    slug: "black-jacket",
    description: "Best women top.Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos voluptatum, accusamus deserunt eius blanditiis recusandae beatae illo  ",
    price: 170,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 20,
  },
  {
    id:5,
    title: "Brown T-shirt",
    image: [
      "/picst/brown-shirt.webp",
      "/picst/brown-shirt0.jpeg",
      "/picst/brown-shirt.jpeg",
    ],
    slug: "brown-shirt",
    description: "Best women top lorem",
    price: 180,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 25,
  },
  {
    id:6,
    title: "Black Stone Neckles",
    image: ["/picsj/blackstoneneckles.webp"],
    slug: "black-stone-neckles",
    description: "Best women accesssories lorem",
    price: 130,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 20,
  },
  {
    id:7,
    title: "brownleather-peep-toe-heel.avif",
    image: ["/picss/brownleather-peep-toe-heel.avif"],
    slug: "brownleather-peep-toe-heel.avif",
    description: "Best women shoes lorem",
    price: 150,
    catogery: "shoes",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },

  {
    id:8,
    title: "Floral Frok",
    image: ["/picst/floralfrock.avif"],
    slug: "floralfrock",
    description: "Best women tops lorem",
    price: 200,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 25,
  },
  {
    id:9,
    title: "Distressed Black Denim Jean",
    image: [
      "/picsp/distressed-black-denim-jean.jpeg",
      "/picsp/distressed-black-denim-jean0.jpeg",
      "/picsp/distressed-black-denim-jean1.jpeg",
      "/picsp/distressed-black-denim-jean2.jpeg"
    ],
    slug: "distressed-black-denim-jean",
    description: "Best women pants lorem",
    price: 150,
    catogery: "pants",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 25,
  },

  {
    id:10,
    title: "Brown Silk Top",
    image: ["/picst/brown-silk-top0.jpeg", "/picst/brown-silk-top1.jpeg"],
    slug: "brown-silk-top",
    description: "Best women top lorem",
    price: 190,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:11,
    title: "Fitted Jeans",
    image: [
      "/picsp/fitjeans.jpeg"
    ],
    slug: "fit-jeans",
    description: "Best women pants lorem",
    price: 170,
    catogery: "pants",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 20,
  },
  {
    id:12,
    title: "Fitted Jeans",
    image: [
      "/picsp/fitjeans.jpeg"
    ],
    slug: "fit-jeans",
    description: "Best women pants lorem",
    price: 150,
    catogery: "pants",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },

  {
    id:13,
    title: "glittered-pointedtoe-heel.avif",
    image: ["/picss/glittered-pointedtoe-heel.avif"],
    slug: "glittered-pointedtoe-heel.avif",
    description: "Best women shoes lorem",
    price: 200,
    catogery: "shoes",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 35,
  },

  {
    id:14,
    title: "Blue Leather Handbag",
    image: ["/picsj/blueleatherhandbag.avif"],
    slug: "blue-leather-handbag",
    description: "Best women accesssories lorem",
    price: 130,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 10,
  },
  {
    id:15,
    title: "lepordprintedshoes.avif",
    image: ["/picss/lepordprintedshoes.avif"],
    slug: "lepordprintedshoes.avif",
    description: "Best women shoes lorem",
    price: 150,
    catogery: "shoes",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:16,
    title: "Elegant Top Skirt Combo",
    image: [
      "/picst/elegantskirt.jpeg",
      "/picst/elegantskirt0.jpeg",
      "/picst/elegantskirt1.jpeg",
    ],
    slug: "elegant-top-skirt-combo",
    description: "Best women top lorem",
    price: 180,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 25,
  },

  {
    id:17,
    title: "Gray Hoodie",
    image: [
      "/picst/grayhoodie.jpeg",
      "/picst/grayhoodie1.jpeg",
      "/picst/grayhoodie3.webp",
    ],
    slug: "gray-hoodie",
    description: "Best women top lorem",
    price: 120,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
 
  {
    id:18,
    title: "Gray Long Sleeve Shirt",
    image: ["/picst/graylongsleeve.jpeg", "/picst/graylongsleeve00.webp"],
    slug: "gray-longsleeve",
    description: "Best women top lorem",
    price: 140,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:19,
    title: "Gray Coat",
    image: [
      "/picst/gray-coat.avif",
    ],
    slug: "gray-coat",
    description: "Best women top lorem",
    price: 190,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },  
  {
    id:20,
    title: "Brown Leather Bag",
    image: ["/picsj/brownleatherbag.avif"],
    slug: "brown-leather-bag",
    description: "Best women accesssories lorem",
    price: 150,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:21,
    title: "Light Blue Jeans",
    image: ["/picsp/lightbluejeans.jpeg"],
    slug: "lightbluejeans",
    description: "Best women pants lorem",
    price: 170,
    catogery: "pants",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 20,
  },
  {
    id:22,
    title: "Black Silk Pants",
    image: [
      "/picsp/blackpant1.avif",
      "/picsp/blackpant2.avif",
      "/picsp/blackpant3.avif"
    ],
    slug: "black-pants",
    description: "Best women pants lorem",
    price: 140,
    catogery: "pants",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },

  {
    id:23,
    title: "Orange Button Shirt",
    image: [
      "/picst/orange-shirt.avif",
  
    ],
    slug: "orange-button-shirt",
    description: "Best women top lorem",
    price: 150,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:24,
    title: "Orange Tucked Neck Shirt",
    image: [
      "/picst/orangeshirt1.avif",
  
    ],
    slug: "orange-tucked-neck-shirt",
    description: "Best women top lorem",
    price: 160,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 25,
  },
  {
    id:25,
    title: "Pink Pointed-Toe Heel",
    image: ["/picss/pinkpointedtoeheel.avif"],
    slug: "pinkpointedtoeheel.avif",
    description: "Best women shoes lorem",
    price: 150,
    catogery: "shoes",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id: 26,
    title: "Brown Leather Wristlet",
    image: ["/picsj/brownleatherwristlet.avif"],
    slug: "brown-leather-wristlet",
    description: "Best women accesssories lorem",
    price: 150,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id: 27,
    title: "Golden Necklace Earring with Watergreen Stone",
    image: ["/picsj/golden-necklace-earring-with-watergreenstone.jpeg"],
    slug: "golden-necklace-earring-with-watergreenstone",
    description: "Best women accesssories lorem",
    price: 150,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id: 28,
    title: "Golden Bangle Bracelet",
    image: ["/picsj/goldenbanglebracelet.webp"],
    slug: "golden-bangle-bracelet",
    description: "Best women accesssories lorem",
    price: 150,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id: 29,
    title: "Golden Ear Piece",
    image: ["/picsj/goldenearpiece.webp"],
    slug: "golden-ear-piece",
    description: "Best women accesssories lorem",
    price: 150,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
{
    id:30,
    title: "Red Aline Frock",
    image: [
      "/picst/red-a-line-dres.jpeg",
      "/picst/red-a-line-midi-dress.jpeg",
      "/picst/red-a-line-midi-dress0.jpeg",
    ],
    slug: "red-a-line-midi-dress",
    description: "Best women top lorem",
    price: 190,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
  {
    id:31,
    title: "White Sleeveless Top",
    image: [
      "/picst/whitesleeveless.avif",
      "/picst/white-sleeveless1.avif"
    ],
    slug: "white-sleeveless-top",
    description: "Best women top lorem",
    price: 160,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 20,
  }, 
  {
    id: 32,
    title: "Golden Stone Ring",
    image: ["/picsj/goldenstonedring.webp"],
    slug: "golden-stone-ring",
    description: "Best women accesssories lorem",
    price: 150,
    catogery: "accessories",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },

  {
    id:33,
    title: "Gray Long Sleeve Shirt",
    image: [
      "/picst/graylongsleeve.jpeg",
      "/picst/graylongsleeve00.webp"
    ],
    slug: "gray-long-sleeve-shirt",
    description: "Best women top lorem",
    price: 140,
    catogery: "tops",
    size: ["S", "M", "L", "Xl"],
    color: ["#ffffff", "#86B6F6", "#7D0A0A"],
    quantity: 1,
    discount: 15,
  },
    
{
  id: 34,
  title: "Brown Long Sleeve Shirt",
  image: [
    "/picst/longsleeve.jpeg",
    "/picst/longsleve.webp"
  ],
  slug: "brown-long-sleeve-shirt",
  description: "Best women top lorem",
  price: 120,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:35,
  title: "rainbowstriped-sandal.avif",
  image: ["/picss/rainbowstriped-sandal.avif"],
  slug: "rainbowstriped-sandal.avif",
  description: "Best women shoes lorem",
  price: 160,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 25,
},
{
  id:36,
  title: "Black Pants",
  image: [
    "/picsp/blackpants.jpeg",
    "/picsp/blackpants1.jpeg",
  ],
  slug: "black-umbrella-pants",
  description: "Best women pants lorem",
  price: 180,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount:20,
},

{
  id:37,
  title: "white-glittered-peep-toe-heeled-shoes.avif",
  image: ["/picss/white-glittered-peep-toe-heeled-shoes.avif"],
  slug: "white-glittered-peep-toe-heeled-shoes.avif",
  description: "Best women shoes lorem",
  price: 170,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount:30,
},
{
  id:38,
  title: "Orange Dress",
  image: [
    "/picst/orange-dress.avif",
    "/picst/orange-dress0.avif"
  ],
  slug: "orange-dress",
  description: "Best women top lorem",
  price: 190,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 25,
},
{
  id: 39,
  title: "Silver Golden Bracelet",
  image: ["/picsj/silvergoldenbracelet.jpeg"],
  slug: "silver-golden-bracelet",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id: 40,
  title: "Silver Neckles",
  image: ["/picsj/silverneckles.jpeg"],
  slug: "silver-neckles",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id: 41,
  title: "White Heart Neckles",
  image: ["/picsj/whiteheart.jpeg","/picsj/whiteheart.webp"],
  slug: "white-heart-neckles",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id: 42,
  title: "White Ring",
  image: ["/picsj/whitering.webp"],
  slug: "white-ring",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},

{
  id:43,
  title: "Blue Dress Pant",
  image: [
    "/picsp/bluedressspants.webp"
  ],
  slug: "blue-dresss-pants",
  description: "Best women pants lorem",
  price: 150,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 0,
},

{
  id:44,
  title: "Khaki Trousers",
  image: [
    "/picsp/khakitrousers.jpeg"
  ],
  slug: "khaki-trousers",
  description: "Best women pants lorem",
  price: 150,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 0,
},
{
  id:45,
  title: "White Sleeveless Top",
  image: [
    "/picst/whitetopskirt.jpeg",
    "/picst/whitetopskirt0.jpeg",
    "/picst/whitetopskirt1.jpeg",
    "/picst/whitetopskirt2.jpeg",
    "/picst/whitetopskirt3.jpeg",
  ],
  slug: "white-top-skirt",
  description: "Best women top lorem",
  price: 170,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},

{
  id:46,
  title: "Golden Earring",
  image: ["/picsj/goldenearring.jpeg"],
  slug: "golden-earring",
  description: "Best women accesssories lorem",
  price: 180,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 25,
},
{
  id:47,
  title: "Golden Neckles Set",
  image: [
    "/picsj/goldennecklesset.webp",
    "/picsj/goldennecklesset0.webp",
    "/picsj/goldennecklesset1.webp"
  ],
  slug: "golden-neckles-set",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 0,
},
  
{
  id:48,
  title: "Navy Blue Pant",
  image: [
    "/picsp/navybluepants.jpeg"
  ],
  slug: "navy-blue-pants",
  description: "Best women pants lorem",
  price: 140,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 10,
},

{
  id:49,
  title: "Golden Pendent",
  image: ["/picsj/goldenpendents.webp"],
  slug: "golden-pendent",
  description: "Best women accesssories lorem",
  price: 180,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 25,
},

{
  id:50,
  title: "Golden Neck Piece",
  image: ["/picsj/golenneckpiece.jpeg"],
  slug: "golden-neck-piece",
  description: "Best women accesssories lorem",
  price: 160,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id: 51,
  title: "OffWhite  Pant",
  image: [
    "/picsp/offwhitepants.avif"
  ],
  slug: "offwhite-pants",
  description: "Best women pants lorem",
  price: 170,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id: 52,
  title: "Gray Pant",
  image: [
    "/picsp/pant.jpeg",
    "/picsp/pant0.jpeg",
    "/picsp/pant1.jpeg"
  ],
  slug: "gray-pants",
  description: "Best women pants lorem",
  price: 160,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id: 53,
  title: "White Trousres",
  image: [
    "/picsp/whitetrousers.webp"
  ],
  slug: "white-trousres",
  description: "Best women pants lorem",
  price: 130,
  catogery: "pants",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:54,
  title: "Black Peep-Toe Heels",
  image: ["/picss/black-peep-toe-heel.avif","/picss/black-peep-toe-heel.avif1.avif"],
  slug: "black-peep-toe-heel",
  description: "Best women shoes lorem",
  price: 130,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 0,
},
{
  id:55,
  title: "Black Leather Peep-Toe Heels",
  image: ["/picss/black-leatherpeeptoe-heel.avif"],
  slug: "black-leatherpeeptoe-heel",
  description: "Best women shoes lorem",
  price: 160,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},

{
  id:56,
  title: "White Printed Shirt",
  image: [
    "/picst/shirt.avif",
    "/picst/shirt0.avif",
    "/picst/shirt1.avif",
  ],
  slug: "white-printed-shirt",
  description: "Best women top lorem",
  price: 170,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:57,
  title: "Black Tucked Neck Shirt",
  image: [
    "/picst/tuckedneck.avif",
    "/picst/tuckedneck1.avif",
  
  ],
  slug: "tuckedneck-shirt",
  description: "Best women top lorem",
  price: 150,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},

{
  id:58,
  title: "Light Stone Pendent",
  image: ["/picsj/light-stone-pendent.webp"],
  slug: "light-stone-pendent",
  description: "Best women accesssories lorem",
  price: 130,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:59,
  title: "White Scoop Neck Top with Black Strap",
  image: [
    "/picst/white-scoop-neck-top-with-black-strap.avif",
    "/picst/white-scoop-neck-top-with-black-strap0.avif",
  
  ],
  slug: "white-scoop-neck-top-with-black-strap",
  description: "Best women top lorem",
  price: 180,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:60,
  title: "Women Gray Button Shirt",
  image: [
    "/picst/women-gray-button-shirt.webp",
  ],
  slug: "women-gray-button-shirt",
  description: "Best women top lorem",
  price: 170,
  catogery: "tops",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},

{
  id:61,
  title: "Black beaded Neckles",
  image: ["/picsj/necklace.jpeg"],
  slug: "black-neckles",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:62,
  title: "Pearl Beaded Bracelet",
  image: ["/picsj/pearlbeadebracelet.jpeg"],
  slug: "pearl-beaded-bracelet",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:63,
  title: "Pink Black Earring",
  image: ["/picsj/pink-black-earring.webp"],
  slug: "pink-black-earring",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:64,
  title: "Leather Bag",
  image: [
    "/picsj/pinkleatherbag.avif",
    "/picsj/purplepurse.avif",
    "/picsj/purplepursr0.avif"
  ],
  slug: "pink-black-earring",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:65,
  title: "Purple Crystal Neckles",
  image: ["/picsj/purplecrystalneckles.jpeg"],
  slug: "purple-crystal-neckles",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:66,
  title: "Blue Stone Ring",
  image: ["/picsj/ring-bluestone.webp"],
  slug: "blue-stone-ring",
  description: "Best women accesssories lorem",
  price: 150,
  catogery: "accessories",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:67,
  title: "Brown Leather Heeled Sandals",
  image: ["/picss/brown-leather-heeled-sandals.avif"],
  slug: "brown-leather-heeled-sandals",
  description: "Best women shoes lorem",
  price: 150,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
{
  id:68,
  title: "leporedprintedsidezipboots.avif",
  image: ["/picss/leporedprintedsidezipboots.avif"],
  slug: "leporedprintedsidezipboots.avif",
  description: "Best women shoes lorem",
  price: 150,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},     
{
  id:69,
  title: "yellow-leather-ankle-strap-sandals.avif",
  image: ["/picss/yellow-leather-ankle-strap-sandals.avif"],
  slug: "yellow-leather-ankle-strap-sandals.avif",
  description: "Best women shoes lorem",
  price: 150,
  catogery: "shoes",
  size: ["S", "M", "L", "Xl"],
  color: ["#ffffff", "#86B6F6", "#7D0A0A"],
  quantity: 1,
  discount: 15,
},
];














export const PeopleId:People[] = [
    {
        id:1,
        name: 'Roneema De Silva' ,
        roll:'Fashion Icon',
        image:i1, 
    },
    {
        id:2,
        name: 'Roneema De Silva' ,
        roll:'Fashion Designer',
        image:i2, 
    },
    {
        id:3,
        name: 'Roneema De Silva' ,
        roll:'Actor',
        image:i3, 
    },
    {
        id:4,
        name: 'Roneema De Silva' ,
        roll:'Model',
        image:i4, 
    },
    {
        id:5,
        name: 'Roneema De Silva' ,
        roll:'Fashoin designer',
        image:i5, 
    },

]


